export const CATEGORY_PROFESSIONAL_KITCHEN = "PROFESSIONAL_KITCHEN";
export const CATEGORY_DELIVERY_TRUCK = "DELIVERY_TRUCK";
export const CATEGORY_STORAGE_SPACE = "STORAGE_SPACE";
export const CATEGORY_OTHER = "OTHER";