export const ORGANIZATION_TYPE_NON_PROFIT_ORGANIZATIONS = "NON_PROFIT_ORGANIZATIONS";
export const ORGANIZATION_TYPE_PRIVATE_COMPANY = "PRIVATE_COMPANY";
export const ORGANIZATION_TYPE_PUBLIC_SECTOR = "PUBLIC_SECTOR";
export const ORGANIZATION_TYPE_OTHER = "OTHER";
